---
- hosts: all
  remote_user: vagrant
  become: yes

  vars:
    java_version: 8
    java_subversion:  77
    java_build: 14

  roles:
    - basic-config
    - williamyeh.oracle-java
    - geerlingguy.ruby
    
